obj-$(CONFIG_SND_SOC_QDSP6) += aac_in.o qcelp_in.o evrc_in.o amrnb_in.o audio_utils.o \
			       audio_wma.o audio_wmapro.o audio_aac.o audio_multi_aac.o audio_utils_aio.o \
			       rtac.o q6audio_v1.o q6audio_v1_aio.o \
			       audio_mp3.o audio_amrnb.o audio_amrwb.o audio_amrwbplus.o audio_evrc.o
obj-$(CONFIG_MSM_QDSP6_APR) += apr.o apr_v1.o apr_tal.o q6core.o dsp_debug.o
obj-$(CONFIG_MSM_QDSP6_APRV2) += apr.o apr_v2.o apr_tal.o q6core.o dsp_debug.o
obj-y += audio_acdb.o
